services:
  splunk:
    platform: linux/amd64
    image: splunk/splunk:latest
    container_name: splunk-indexer
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_ACCEPT_LICENSE=yes
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - ./data:/tmp/data
    networks:
      - soc-net

  attack-simulator:
    image: python:3.9-slim
    container_name: attack-generator
    volumes:
      - ./data:/data/var/log/attacks
    networks:
      - soc-net
    depends_on:
      - splunk
    command: tail -f /dev/null

networks:
  soc-net:
    driver: bridge