[credential:postgres:do.root:]
password = $7$OovZB36o+SXXjwwswIugvWakmUOdwv4qZVI93I73LGM5IoOq5iAteP0GTVEFhGBbq9DU1RV2r4cQX+pRiRoM1A==

[credential:postgres:do.dbuser:]
password = $7$tr5Fh8LNGqbGM3RkjZDChG5uXDcp36TwkX7UIxAJM/Qq8oDf47vsMvTcWCcJcf80a09GYdLFnZUkldqmtUS4yw==

[credential:postgres:kvstore.pdl:]
password = $7$omJGs9kAHHoVlOZIsDnlnJwcrYcoEA5Ul/MbMUgQddIW7YIiNMvu5yfxYLxXLLERmiJq5zXia+dFft8tKJ/o6w==

[credential:postgres:acc.dbuser:]
password = $7$bue/YvVKwu//T4XuqFjpYFSZYqXWryQI3IWQBV+VocAqWxV0o0WqCIQTF+UQYq/4/xo0feqHcHISsLL2aQmPGQ==

[credential:postgres:oas.root:]
password = $7$/bDkkOVRAq1Sq96i35lzjWI8gQ6/vCwq2gO/DC/sHRALR7Yr8bQ3TYmKD5yOZGGv/ml3bPF8tr/xuPGWgStZYA==

[credential:postgres:oas.dbuser:]
password = $7$6/jSp1Z6YcMCdYai8yMORbsH1O7okZOUd3LsV2hJKqDOcK3+AX8UAydpB6ga695lJH4ShNYuExHdmx5kid17ew==

[credential:postgres:deployment_guid:]
password = $7$Mf8Zf7OyeWQ/91yScqfaEionAHbZOAgKsqYt8IvJGCOYD58V4XvsMhl9I6j3J8rmYJG6EtHXMJJ/EKRrGW+/VxVPUUEC0o5E16ixoFNSJw==

[credential:postgres:postgres_admin:]
password = $7$RfsqNlKsqE0UauqyIa0RaeT5UzMwphKRlFjpVTKCkvTF97kjLTnzv9EZO56+VYXULpl45fpXwnyDS3ria9riQw==
