[general]
serverName = dae080012dc8
pass4SymmKey = $7$rDZNzpTU68enFVWZ22yOfLEKeV94HzBk2vl+uBTocwUu6zxVBr0z2A==

[sslConfig]
sslPassword = $7$N5VJpc+qCFH6TWhFd9sgPl873shwyX6RO7t4m/daqMPxhaGLOQ+X5Q==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
